apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: gdb
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE DATABASE auth_db;
        CREATE DATABASE users_db;
        CREATE DATABASE accounts_db;
        CREATE DATABASE trasaction_db;
    EOSQL

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: gdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: gdb-config
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gdb-secret
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: gdb-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-db.sh
              subPath: init-db.sh
      volumes:
        - name: init-script
          configMap:
            name: postgres-init-script
            defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: gdb
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-db
