server:
  port: 8002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction
    username: postgres
    password: java
  flyway:
    enabled: true

logging:
  level:
    com.gdb.transactions: DEBUG
